/* eslint-disable no-console */
var width = 10;
var height = 5;
var area = height * width;
var bill = 2;
var payment = 11;
var change = payment - bill;
var quizzes = 20;
var midterm = 80;
var final = 100;
var grade = (quizzes + midterm + final) / 3;
var firstName = 'Adrian';
var lastName = 'Gonzalez';
var fullName = firstName + ' ' + lastName;
var pH = 5;
var isAcidic = pH < 7;
var headCount = 45;
var isSparta = headCount === 300;
var motto = fullName + ' ' + 'is the GOAT';

console.log('value of area: ', area);
console.log('typeof area: ', typeof area);
console.log('value of change: ', change);
console.log('typeof change: ', typeof change);
console.log('value of grade: ', grade);
console.log('typeof grade: ', typeof grade);
console.log('value of fullName: ', fullName);
console.log('typeof fullName:', typeof fullName);
console.log('value of isAcidic: ', isAcidic);
console.log('typeof isAcidic: ', typeof isAcidic);
console.log('value of isSparta: ', isSparta);
console.log('typeof isSparta: ', typeof isSparta);
console.log('value of motto: ', motto);
console.log('typeof motto: ', typeof motto);
